xfce4-notifyd
xfce4-taskmanager
xfce4-screenshooter
orage
vte2
xfce4-terminal
xfce4-dict
xfce4-clipman-plugin
xfce4-systemload-plugin
xfce4-netload-plugin
xfce4-wavelan-plugin
xfce4-weather-plugin
xfce4-xkb-plugin
xfce4-sensors-plugin
xfce4-cpufreq-plugin
xfce4-places-plugin
thunar-archive-plugin
xfce4-whiskermenu-plugin
libunique
xfce4-notes-plugin
gstreamer0
gst0-plugins-base
gst0-plugins-good
xfce4-mixer
xfce4-volumed-pulse
