xfce4-dev-tools
libxfce4util
xfconf
libxfce4ui
exo
garcon
xfce4-panel
thunar
thunar-volman
tumbler
xfce4-appfinder
xfce4-power-manager
xfce4-settings
xfdesktop
xfwm4
xfce4-session
xfce4-notifyd
xfce4-taskmanager
xfce4-screenshooter
orage
vte2
xfce4-terminal
xfce4-dict
xfce4-clipman-plugin
xfce4-systemload-plugin
xfce4-netload-plugin
xfce4-wavelan-plugin
xfce4-weather-plugin
xfce4-xkb-plugin
xfce4-sensors-plugin
xfce4-cpufreq-plugin
xfce4-places-plugin
thunar-archive-plugin
xfce4-whiskermenu-plugin
libunique
xfce4-notes-plugin
gstreamer0
gst0-plugins-base
gst0-plugins-good
xfce4-mixer
xfce4-volumed-pulse
gnome-icon-theme
gtk-xfce-engine
xfwm4-themes
evince-gtk2
file-roller-gtk2
gcalctool-gtk2
gigolo-gtk2
gtksourceview
mousepad-gtk2
goffice0.8
gnumeric-gtk2
brasero-gtk2
python-webencodings
html5lib
setuptools-scm
functools-lru-cache
python-soupsieve
BeautifulSoup4
lxml
numpy
potrace
inkscape-gtk2
