tales-xfce4-dev-tools
tales-libxfce4util
tales-xfconf
tales-libxfce4ui
tales-exo
tales-garcon
tales-xfce4-panel
tales-thunar
tales-thunar-volman
tales-tumbler
tales-xfce4-appfinder
tales-xfce4-power-manager
tales-xfce4-settings
tales-xfdesktop
tales-xfwm4
tales-xfce4-session
tales-xfce4-clipman-plugin
tales-xfce4-notifyd
tales-xfce4-screenshooter
tales-xfce4-systemload-plugin
tales-xfce4-taskmanager
vte2
tales-xfce4-terminal
tales-xfce4-weather-plugin
tales-xfce4-whiskermenu-plugin
orage
thunar-archive-plugin
xfce4-cpufreq-plugin
xfce4-dict
xfce4-netload-plugin
xfce4-places-plugin
xfce4-sensors-plugin
xfce4-wavelan-plugin
xfce4-xkb-plugin
libunique
xfce4-notes-plugin
