xfce4-dev-tools
libxfce4util
xfconf
libxfce4ui
exo
garcon
xfce4-panel
thunar
thunar-volman
tumbler
xfce4-appfinder
xfce4-power-manager
xfce4-settings
xfdesktop
xfwm4
xfce4-session
xfce4-clipman-plugin
xfce4-notifyd
xfce4-pulseaudio-plugin
xfce4-screenshooter
xfce4-systemload-plugin
xfce4-taskmanager
xfce4-terminal
xfce4-weather-plugin
xfce4-whiskermenu-plugin
orage
thunar-archive-plugin
xfce4-cpufreq-plugin
xfce4-dict
xfce4-netload-plugin
xfce4-places-plugin
xfce4-sensors-plugin
xfce4-wavelan-plugin
xfce4-xkb-plugin
libunique
xfce4-notes-plugin
gtk-xfce-engine
xfwm4-themes
